server: 
  port: 8080
  servlet:
    context-path: /personal
spring:
  application:
    name: personal
  datasource:
    db1:
      url: jdbc:mysql://localhost:3306/personal?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: root
      password: liqing
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    db2:
      url: jdbc:mysql://localhost:3306/personal_sec?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: root
      password: liqing
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 30000
      time-between-eviction-runs-millis: 60000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
mybatis:
  type-aliases-package: com.personal.lq.entity
  mapper-locations: classpath:mapper/*.xml
